combined_modeling:
  target_currency: "USD_SGD"

  merge_strategy:
    news_tolerance: "6H"  # Maximum age of news to associate with market data
    market_primary: true  # Use market timestamps as primary
    fill_missing_news: true  # Fill missing news with neutral values

  feature_selection:
    market_features:
      core: ["mid", "spread", "ret_1", "ret_5", "roll_vol_20", "zscore_20", "bid_liquidity", "ask_liquidity"]
      extended: ["ewma_signal", "spread_pct", "total_liquidity", "effective_spread", "vol_20", "high_vol_regime"]
      all: ["*"]  # Include all available market features

    news_features:
      core: ["news_sentiment", "news_directional_signal", "news_signal_strength", "news_article_count"]
      extended: ["news_quality_score", "news_time_decay", "dominant_policy_tone", "signal_consensus"]
      all: ["*"]  # Include all available news features

  models:
    logistic_regression:
      enabled: true
      params:
        max_iter: 1000
        random_state: 42

    random_forest:
      enabled: true
      params:
        n_estimators: 100
        random_state: 42
        n_jobs: -1

    gradient_boosting:
      enabled: true
      params:
        n_estimators: 100
        random_state: 42
        learning_rate: 0.1

  evaluation:
    test_size: 0.2
    cross_validation: true
    cv_folds: 5
    scoring_metrics: ["roc_auc", "accuracy", "precision", "recall", "f1"]

  preprocessing:
    scale_features: true
    handle_missing: "median"  # Options: "median", "mean", "zero", "drop"
    remove_outliers: true
    outlier_threshold: 5  # Standard deviations
    correlation_threshold: 0.95  # Remove highly correlated features

  output:
    save_models: true
    save_predictions: true
    save_feature_importance: true
    save_metrics: true

pipeline_coordination:
  market_pipeline:
    bronze_input: "data/market/bronze/prices/"
    silver_output: "data/market/silver/"
    gold_output: "data/market/gold/training/market_features.csv"

  news_pipeline:
    bronze_input: "data/news/bronze/raw_articles/"
    silver_output: "data/news/silver/"
    gold_output: "data/news/gold/news_signals/trading_signals.csv"

  combined_output:
    models_dir: "data/combined/models/"
    training_data: "data/combined/training/"
    predictions_dir: "data/combined/predictions/"

refresh_strategy:
  market_features:
    frequency: "continuous"  # Process every new tick batch
    batch_size: 100

  news_features:
    frequency: "event_driven"  # Process when new articles arrive
    batch_size: 10

  combined_modeling:
    frequency: "hourly"  # Retrain combined models hourly
    min_new_observations: 50

monitoring:
  feature_drift:
    enabled: true
    window_size: 1000
    alert_threshold: 0.1  # Statistical distance threshold

  model_performance:
    enabled: true
    retraining_threshold: 0.05  # AUC drop threshold
    evaluation_window: 500

  data_quality:
    missing_rate_threshold: 0.2
    outlier_rate_threshold: 0.05
    feature_correlation_check: true