features:
  mid:
    description: "Mid-price constructed from top-of-book bid/ask"
  spread:
    description: "Top-of-book ask minus bid (in price units)"
  ret_1:
    window: 1
    description: "One-tick percentage return"
  ret_5:
    window: 5
    description: "Five-tick percentage return"
  roll_vol_20:
    window: 20
    description: "Rolling volatility of one-tick returns"
  zscore_20:
    window: 20
    description: "Rolling z-score of the mid-price"
  bid_liquidity:
    description: "Liquidity associated with the best bid quote"
  ask_liquidity:
    description: "Liquidity associated with the best ask quote"
news_features:
  sentiment_score:
    description: "Lexicon-based sentiment score (-1 to 1)"
  mentions_sgd:
    description: "Binary flag if the story references SGD or Singapore"
  word_count:
    description: "Token count of the article body"
  news_age_minutes:
    description: "Minutes between latest story and observed price tick"
  news_source:
    description: "Origin of the story (e.g. curated, provider)"
label:
  horizon: 5
  description: "Binary label: 1 if mid-price rises within 5 ticks"
