market_features:
  technical:
    mid:
      description: "Mid-price constructed from top-of-book bid/ask"
    spread:
      description: "Top-of-book ask minus bid (in price units)"
    ret_1:
      window: 1
      description: "One-tick percentage return"
    ret_5:
      window: 5
      description: "Five-tick percentage return"
    roll_vol_20:
      window: 20
      description: "Rolling volatility of one-tick returns"
    zscore_20:
      window: 20
      description: "Rolling z-score of the mid-price"
    ewma_short:
      window: 5
      description: "Short-term exponentially weighted moving average"
    ewma_long:
      window: 20
      description: "Long-term exponentially weighted moving average"
    ewma_signal:
      description: "Difference between short and long EWMA"

  microstructure:
    bid_liquidity:
      description: "Liquidity associated with the best bid quote"
    ask_liquidity:
      description: "Liquidity associated with the best ask quote"
    total_liquidity:
      description: "Combined bid and ask liquidity"
    liquidity_imbalance:
      description: "Normalized difference between ask and bid liquidity"
    effective_spread:
      description: "Spread as percentage of mid-price"
    quoted_depth:
      description: "Minimum of bid and ask liquidity"
    liquidity_shock:
      description: "Deviation from average liquidity levels"

  volatility:
    vol_5:
      window: 5
      description: "5-tick realized volatility (annualized)"
    vol_20:
      window: 20
      description: "20-tick realized volatility (annualized)"
    vol_60:
      window: 60
      description: "60-tick realized volatility (annualized)"
    range_vol:
      window: 5
      description: "Range-based volatility estimate"
    vol_percentile:
      window: 100
      description: "Volatility percentile rank"
    high_vol_regime:
      description: "Binary indicator for high volatility periods"
    low_vol_regime:
      description: "Binary indicator for low volatility periods"

  derived:
    hour:
      description: "Hour of day (0-23)"
    day_of_week:
      description: "Day of week (0=Monday, 6=Sunday)"
    is_weekend:
      description: "Binary indicator for weekend periods"
    asian_session:
      description: "Binary indicator for Asian trading session"
    london_session:
      description: "Binary indicator for London trading session"
    ny_session:
      description: "Binary indicator for New York trading session"
    usd_sgd_eur_usd_corr:
      window: 50
      description: "Rolling correlation between USD_SGD and EUR_USD"
    relative_performance:
      description: "Performance relative to currency basket"

target:
  y:
    horizon: 5
    description: "Binary label: 1 if mid-price rises within 5 ticks"

quality_filters:
  min_obs_per_instrument: 100
  max_missing_rate: 0.1
  outlier_threshold: 5  # Standard deviations from mean